### ISSUE TITLE
Les chaines de langue complexe

### ISSUE THREAD

**Issue by phenix-factory** [bystrano/web-mode#5]
Hop ! 

Les chaines de langues complexes sont mal gérées. Ça va pas être de la tarte par contre :

![chaine de lanage SPIP complexe](https://cloud.githubusercontent.com/assets/1810149/17926849/4088e4d0-69f3-11e6-8584-4205ceb5d9ce.png)

Avec ou sans le local, il n'y a aucune coloration.

**Comment by bystrano** [comment]
ça devrait être corrigé maintenant. Les balises à l'intérieur ne sont pas détectées, mais ça c'est une autre paire de manches. Pour moi ça serait trop d'effort par rapport à ce que ça apporte au final...
