### ISSUE TITLE
Balise et string html

### ISSUE THREAD

**Issue by phenix-factory** [bystrano/web-mode#6]
Yop
Un autre petit bug : la coloration des balises SPIP dans les chaines de caractères ne fonctionnent pas totalement :

![selection_004](https://cloud.githubusercontent.com/assets/1810149/17933588/f2aaa416-6a14-11e6-80e0-90d7e5b53384.png)

**Comment by bystrano** [comment]
En fait le moteur de coloration spip ne colore pas les parenthèses, c'est le mode show-smartparen-mode qui s'en charge. Et lui ne fonctionne pas dans les attributs html…

Du coup je pense que c'est plutôt du côté de smartparen qu'il faut régler ce problème.
